import {ColumnAutoGenerationStrategy} from '../orm.types';
import {declareEntity} from '../helpers';

export function AutoGenerated(strategy: ColumnAutoGenerationStrategy): PropertyDecorator {
    return (target: Object, propertyKey: string | symbol): void => {
        if (typeof propertyKey !== 'string')
            throw new Error('You can define a Column for only string properties');
        declareEntity(target.constructor)
            .defineDataColumn(propertyKey, {autoGenerate: strategy})
    }
}
