import {AutoGenerationStrategy} from '../types';
import {EntityDefinition} from '../definition/EntityDefinition';

export function AutoGenerated(strategy: AutoGenerationStrategy): PropertyDecorator {
    return (target: Object, propertyKey: string | symbol): void => {
        if (typeof propertyKey !== 'string')
            throw new Error('You can define a Column for only string properties');
        const entity = EntityDefinition.attach(target.constructor);
        const col = entity.addDataColumn(propertyKey);
        col.autoGenerate = strategy;
    }
}
