import {
    DataType,
    BaseEntity,
    Embedded,
    Column,
    Entity,
    PrimaryKey,
    Parse,
    Serialize,
    LinkToOne, LinkFromOne, Link, linkToOne, linkFromMany, linkFromOne,
} from '@sqb/connect';
import {PersonName} from './person-name.type';
import {Country} from '../_support/country.entity';
import {CustomerDetail} from './customer-detail.entity';
import {Continent} from '../_support/continent.entity';
import {CustomerTag} from '../_support/customer-tag.entity';
import {Tag} from '../_support/tags.entity';
import {CustomerVip} from '../_support/customer-vip.entity';
import {Address} from './address';

const GenderMap = {
    M: 'Male',
    F: 'Female'
}

@Entity('customers')
export class Customer extends BaseEntity {
    @PrimaryKey()
    @Column({fieldName: 'ID', dataType: DataType.BIGINT, autoGenerated: 'increment'})
    id?: number;

    @Column({fieldName: 'given_name'})
    givenName?: string;

    @Column({fieldName: 'family_name'})
    familyName?: string;

    @Embedded(PersonName)
    name: PersonName;

    @Column({
        fieldName: 'birth_date',
        dataType: DataType.DATE,
    })
    birthDate?: Date;

    @Column()
    city?: string;

    @Column({fieldName: 'country_code', notNull: true})
    countryCode?: string;

    @Column({
        fieldName: 'created_at',
        dataType: DataType.TIMESTAMP,
        autoGenerated: 'timestamp',
        noUpdate: true
    })
    createdAt?: Date;

    @Column(DataType.CHAR)
    @Parse((v) => GenderMap[v] || 'Unknown')
    @Serialize((v) => ('' + v).charAt(0))
    gender: string;

    @Embedded(Address, {fieldNamePrefix: 'address_'})
    address: Address;

    @Column({
        fieldName: 'updated_at',
        dataType: DataType.TIMESTAMP,
        autoGenerated: 'timestamp',
        noInsert: true
    })
    updatedAt?: Date;

    @Column({default: true})
    active: boolean;

    @Column()
    vip: boolean;

    @Column({fieldName: 'custom_data', dataType: DataType.JSON})
    customData: object;

    @LinkToOne()
    readonly country?: Country;

    @Link(linkFromOne(CustomerVip))
    readonly vipDetails: CustomerVip;

    @Link(linkFromOne(CustomerVip)
        .where({'rank>=': 5}))
    readonly vvipDetails: CustomerVip;

    @Link(linkToOne(Country).linkToOne(Continent))
    readonly continent: Continent;

    @LinkFromOne(CustomerDetail)
    readonly details: CustomerDetail;

    @Link(linkFromMany(CustomerTag).linkToMany(Tag))
    readonly tags?: Tag[];

}
