import {
    DataType,
    BaseEntity,
    Column,
    Entity,
    HasOne,
    PrimaryKey,
    LazyResolver,
    AutoGenerated,
    ForeignKey,
    FieldName,
    NoUpdate,
    Parse,
    Serialize, NoInsert, HasOneLazy,
} from '@sqb/connect';
import {Country} from './countries.entity';
import {Embedded} from '@sqb/connect';
import {PersonName} from '../_support/person-name.entity';

const GenderMap = {
    M: 'Male',
    F: 'Female'
}

@Entity('customers')
export class Customer extends BaseEntity<Customer> {
    @PrimaryKey()
    @Column(DataType.BIGINT)
    @FieldName('ID')
    @AutoGenerated('increment')
    id?: number;

    @FieldName('given_name')
    givenName?: string;

    @FieldName('family_name')
    familyName?: string;

    @Embedded(PersonName)
    name: PersonName;

    @Column({
        fieldName: 'birth_date',
        dataType: DataType.DATE,
    })
    birthDate?: Date;

    @Column()
    city?: string;

    @FieldName('country_code')
    @ForeignKey(Country)
    countryCode?: string;

    @Column(DataType.TIMESTAMP)
    @FieldName('created_at')
    @AutoGenerated('timestamp')
    @NoUpdate
    createdAt?: Date;

    @Column(DataType.CHAR)
    @Parse((v) => GenderMap[v] || 'Unknown')
    @Serialize((v) => ('' + v).charAt(0))
    gender: string;

    @Column(DataType.TIMESTAMP)
    @AutoGenerated('timestamp')
    @FieldName('updated_at')
    @NoInsert
    updatedAt?: Date;

    @HasOne(Country)
    readonly country?: Country;

    @HasOneLazy(Country)
    readonly countryLazy?: LazyResolver<Country>;

    /* @HasMany(CustomerTag, 'id>customerId', Through(String, '')
    )
    readonly tags?: CustomerTag[];*/

    /*  */

}
