import {AutoGenerated, Column, Default, Entity, Enum, PrimaryKey} from '@sqb/connect';

@Entity({tableName: 'tags'})
export class Tag {
    @PrimaryKey()
    @AutoGenerated('increment')
    id: number;

    @Column()
    name: string;

    @Column()
    @Default(true)
    active: boolean = true;

    @Column()
    @Enum(['red', 'green', 'blue', 'yellow', 'brown', 'white'])
    @Default((obj) => {
        if (obj.tag === 'small')
            return 'yellow'
        if (obj.tag === 'generous')
            return 'green'
        if (obj.tag === 'large')
            return 'orange'
        if (obj.tag === 'stingy')
            return 'red'
    })
    color: string;
}
