import type {AbstractElementMeta} from './metadata/abstract-element-meta';
import type {Repository} from './repository';
import {DataType, Type} from '..';

/* Model related */
export type ElementKind = 'data' | 'relation' | 'embedded';

/**
 * Indicates auto generation strategy
 */
export type ColumnAutoGenerationStrategy = 'increment' | 'uuid' | 'rowid' |
    'timestamp' | 'custom';

export type ColumnTransformFunction = (value: any, col: AbstractElementMeta, row: any) => any;

export type ConstructorResolver<T> = () => Type<T> | Promise<Type<T>>;
export type ConstructorThunk<T = any> = Type<T> | ConstructorResolver<T>;

export type LazyResolver<T> = (options?: Repository.FindAllOptions) => Promise<T>;

export type EnumValue = (FieldValue)[] | Object;

export type FieldValue = string | number | boolean | Date | null;
export type DefaultValueGetter = (obj?: any)=> FieldValue;

export interface EntityConfig {
    /**
     *  Name of the table name. Default: entity class name.
     */
    tableName?: string;

    /**
     * Schema name which entity belongs to
     */
    schema?: string;

    /**
     * Table comment
     */
    comment?: string;
}

export interface IndexOptions {
    /**
     *  Name of the index
     */
    name?: string;

    /**
     * Specifies if index is unique
     */
    unique?: boolean;
}

export interface ForeignKeyOptions {
    /**
     *  Name of the index
     */
    name?: string;

    keyColumn?: string;
    targetColumn?: string;

}

export interface ColumnOptions {
    /*
      JS type
     */
    type?: Function;

    /**
     * Column data type
     */
    dataType?: DataType;

    /**
     * Field name in the database table. Default: property name
     */
    fieldName?: string;

    /**
     * Field comment
     */
    comment?: string;

    /**
     * Character or byte length of column
     */
    length?: number;

    /**
     * Column's default value
     */
    defaultValue?: FieldValue | DefaultValueGetter;

    /**
     * The precision for a decimal field
     */
    precision?: number;

    /**
     * The scale for a decimal field
     */
    scale?: number;

    /**
     * Fields's collation.
     */
    collation?: string;

    /**
     * Indicates auto generation strategy
     */
    autoGenerated?: ColumnAutoGenerationStrategy;

    /**
     * Indicates enum values
     */
    enum?: EnumValue;

    /**
     * Indicates if column value can be null
     */
    notNull?: boolean;

    /**
     * Indicates whether or not to hide this column by default when making queries.
     */
    hidden?: boolean;

    /**
     * Indicates if column value is used in update queries
     */
    noUpdate?: boolean;

    /**
     * Indicates if column value is used in insert queries
     */
    noInsert?: boolean;
}

export interface EmbeddedTypeOptions {
    fieldNamePrefix?: string;
    fieldNameSuffix?: string;
}

export interface RelationColumnOptions {
    hasMany?: boolean;
    lazy?: boolean;
}

export interface RelationLink {

}
