/* eslint-disable @typescript-eslint/unbound-method,@typescript-eslint/no-unused-vars */
import '../../_support/env';
import * as assert from 'assert';
import {AutoGenerated, Entity} from '@sqb/connect';

describe('Generated()', function () {

    it(`should add column metadata and set "autoGenerate" option`, () => {
        class MyEntity {
            @AutoGenerated('uuid')
            id: string
        }

        const meta = Entity.getMetadata(MyEntity);
        assert.ok(meta);
        assert.strictEqual(meta.name, 'MyEntity');
        const idColumn = meta.getDataColumn('id');
        assert.ok(idColumn);
        assert.strictEqual(idColumn.autoGenerate, 'uuid');
    });

});
